### ISSUE TITLE
User auth

### ISSUE THREAD

**Issue by itsmargaret** [itsmargaret/pinterest-clone#2]
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Hey, overall good job! All the functionality seems to be there. I just have a couple of comments on styling:

1. The background is darker on Pinterest's actual website compared to yours, and I think this actually makes a pretty significant difference. I think it's just a matter of changing the opacity of the background.
2. Lessen the amount of space between the photos, yours have about 2-3x the padding as Pinterest's
3. Not a huge deal, but the 'Sign Up'/'Log In' button in the upper left corner overlaps with the pictures on Pinterest's site but does not on yours. 
![Screen Shot 2020-01-09 at 2 30 43 PM](https://user-images.githubusercontent.com/32026924/72110584-6ae12780-32ed-11ea-951f-b06a651d3c7e.png)
![Screen Shot 2020-01-09 at 2 30 46 PM](https://user-images.githubusercontent.com/32026924/72110585-6ae12780-32ed-11ea-9b5a-829bdb32a37c.png)
4. Give the error messages that show up in the session form red text.
5. Remove your logger from production (look at the code snippet that I sent to the advisee group).
